/*
Markov.coffee - Markov chains in CoffeeScript.
github.com/SyntaxColoring/Markov-Word-Generator

Released under the MIT license.

Copyright (c) 2013 Max Marrone

Permission is hereby granted, free of charge, to any person obtaining a copy of
this software and associated documentation files (the "Software"), to deal in
the Software without restriction, including without limitation the rights to
use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
the Software, and to permit persons to whom the Software is furnished to do so,
subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */
var Markov;

Markov = (function() {
  function Markov(sequences, n1, maxLength) {
    this.sequences = sequences != null ? sequences : [];
    this.n = n1 != null ? n1 : 2;
    this.maxLength = maxLength != null ? maxLength : 20;
  }

  Markov.prototype.generate = function() {
    var continuation, currentState, nextElement, result;
    result = [];
    currentState = (function(_this) {
      return function() {
        return result.slice(Math.max(0, result.length - _this.n), result.length);
      };
    })(this);
    continuation = (function(_this) {
      return function() {
        return _this["continue"](currentState());
      };
    })(this);
    while (result.length < this.maxLength && ((nextElement = continuation()) != null)) {
      result.push(nextElement);
    }
    return result;
  };

  Markov.prototype.ngrams = function() {
    var ngramsFromSequence;
    ngramsFromSequence = function(sequence, n) {
      var i, j, ref, results;
      if (n < 1 || n > sequence.length) {
        return [];
      } else {
        results = [];
        for (i = j = 0, ref = sequence.length - n; 0 <= ref ? j <= ref : j >= ref; i = 0 <= ref ? ++j : --j) {
          results.push(sequence.slice(i, i + n));
        }
        return results;
      }
    };
    return this.sequences.reduce(((function(_this) {
      return function(a, b) {
        return a.concat(ngramsFromSequence(b, _this.n + 1));
      };
    })(this)), []);
  };

  Markov.prototype.tree = function(sequence) {
    var element, j, k, len, len1, ngram, ngrams, node, normalize, reduce, root;
    if (sequence == null) {
      sequence = [];
    }
    ngrams = this.ngrams();
    root = {
      continuations: {},
      count: ngrams.length,
      frequency: 1.0
    };
    for (j = 0, len = ngrams.length; j < len; j++) {
      ngram = ngrams[j];
      node = root;
      for (k = 0, len1 = ngram.length; k < len1; k++) {
        element = ngram[k];
        if (node.continuations[element] == null) {
          node.continuations[element] = {
            continuations: {},
            count: 0
          };
        }
        node = node.continuations[element];
        node.count++;
      }
    }
    normalize = function(node) {
      var child, childName, ref, results;
      ref = node.continuations;
      results = [];
      for (childName in ref) {
        child = ref[childName];
        child.frequency = child.count / node.count;
        results.push(normalize(child));
      }
      return results;
    };
    normalize(root);
    if (typeof sequence === "string") {
      sequence = sequence.split("");
    }
    reduce = function(node, element) {
      var ref;
      if (node != null) {
        return (ref = node.continuations[element]) != null ? ref : null;
      } else {
        return null;
      }
    };
    return sequence.reduce(reduce, root);
  };

  Markov.prototype["continue"] = function(sequence) {
    var continuationName, continuationNode, node, ref, sum, target;
    node = this.tree(sequence);
    if (node != null) {
      target = this.rng.next();
      sum = 0;
      ref = node.continuations;
      for (continuationName in ref) {
        continuationNode = ref[continuationName];
        sum += continuationNode.frequency;
        if (sum >= target) {
          return continuationName;
        }
      }
    }
    return null;
  };

  return Markov;

})();

if (typeof module !== "undefined" && module !== null) {
  module.exports = Markov;
} else {
  this.Markov = Markov;
}

// ---
// generated by coffee-script 1.9.2